WIP: Better readme
ktk-2005/Feedbacker-Forum pull request #107
Opened 2019-04-03 12:49 UTC by tobbe-j

Better readme to help new users or developers.

## Review Checklist

- [ ] All changes are described in the PR description
- [ ] New feature and breaking changes have documentation
- [ ] New endpoints have API tests
- [ ] New frontend features have Enzyme tests
- [ ] No unnecessary or debugging code
- [ ] Questionable code is clearly marked with comments
- [ ] Manually tested with latest Firefox, Safari and Chrome

2019-04-03 12:50 UTC, tobbe-j commented
![](https://github.trello.services/images/mini-trello-icon.png) [[task] [misc] Better github readme, prep for open source Tobias](https://trello.com/c/eJn5hlmv/171-task-misc-better-github-readme-prep-for-open-source-tobias)

2019-04-03 13:48 UTC, HenrikHelenius requested changes

2019-04-03 13:48 UTC, HenrikHelenius commented on README.md
> +[aalto]: https://aalto.fi
https://www.aalto.fi/department-of-computer-science

2019-04-03 13:56 UTC, HenrikHelenius requested changes

2019-04-03 13:56 UTC, HenrikHelenius commented on README.md
> +This project was started during the course CS-C2130 Software Project at [Aalto University][aalto] for the company [Sievo][sievo].
Tag github users

2019-04-03 14:04 UTC, HenrikHelenius requested changes

2019-04-03 14:04 UTC, HenrikHelenius commented on README.md
> +This project was started during the course CS-C2130 Software Project at [Aalto University][aalto] for the company [Sievo][sievo].
The project was supported by Sievo

2019-04-03 16:42 UTC, HenrikHelenius commented on README.md
> +<img src="docs/images/feedbacker-logo.png" height="50%" width="50%">
is margin possible? add negative space under

2019-04-03 16:45 UTC, HenrikHelenius commented on README.md
> +Demo video [Feedbacker-Forum](https://www.youtube.com/watch?v=bkxmN-j-ae0)
Fake video embed like this: https://stackoverflow.com/questions/4279611/how-to-embed-a-video-into-github-readme-md

2019-04-03 16:46 UTC, HenrikHelenius commented on README.md
> +You can request access to try out Feedbacker-forum from [Feedbacker.site](https://feedbacker.site/about/)
Remove this, just put it like bla bla landing page: /about etc

2019-04-03 16:47 UTC, HenrikHelenius commented on README.md
> +The project was created by
created by:

2019-04-03 17:16 UTC, bqqbarbhg commented on README.md
> +- [@bqqbarbhg](https://github.com/bqqbarbhg)
Why namedropping?

2019-04-04 13:30 UTC, tobbe-j commented on README.md
> +- [@bqqbarbhg](https://github.com/bqqbarbhg)
Considered unnecessary, removed

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +The developer can then create surveys, recieve answers and discuss the live UI with peers.
recieve -> receive

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +Feedbacker-Forum also supports creating "feedback-able" links for existing external websites [/about](https://feedbacker.site/about/).
what is the meaning of this /about?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +The project consist of a frontend, backend, proxy and database. The different parts can either be setup manually, or run together using containers.
The project -> the application?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +The project also requires [go][golang] version 1.11 for running the proxy.
project -> application?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +The dashboard view is for developers to add, remove and manage instances.
add -> create?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +After creating an instance the developer recieves a simple link that can be shared, so that people easily can view the instance and give feedback.
recieves -> receives

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +After creating an instance the developer recieves a simple link that can be shared, so that people easily can view the instance and give feedback.
people can easily view

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +* Automatically deploy your app from git, boh public repos and private Github repos supported
boh -> both, repos or repositorys?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +* Easily discuss and cultivate ideas with theaded discussion, no blocking signup required
threaded discussion

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +* Specify the feedback recieved by creating surveys with normal or multiple choice questions
received

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +* Specify the feedback recieved by creating surveys with normal or multiple choice questions
free form or multiple choice questions?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +* Boost productivity by integrating Feedbacker-Forum to slack with a SlackBot
Slack

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +The project is still in a quite early development stage and is actively being developed.
project -> application?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +Changes or additions can be proposed by creating issues or pull requests on github. Running a local development version can be setup as seen in [Setting Up](#Setting-up).
as seen in -> as shown in?

2019-04-04 13:50 UTC, joonalillfors commented on README.md
> +The project contains has style checking using [eslint][eslint] with a slightly modified [airbnb-config][airbnb-config].
the project contains has

2019-04-04 13:51 UTC, joonalillfors commented on README.md
> +Feedbacker-Forum also supports creating "feedback-able" links for existing external websites [/about](https://feedbacker.site/about/).
it doesn't quite flow with the sentence

2019-04-04 16:25 UTC, quvide commented on README.md
> +If the application is run with containers [docker-compose][docker-compose] is also required for orchestrating the containers.
What does this mean? Docker-compose is not required when not running the app backend itself outside of docker

2019-04-04 16:47 UTC, HenrikHelenius approved these changes
🎃🎃🎃🎃🎃🎃🎃🎃🎃

2019-04-04 17:00 UTC, merged