Don't override databaseUrl from env var if not set
ktk-2005/Feedbacker-Forum pull request #32
Opened 2019-01-31 19:07 UTC by quvide

2019-01-31 20:23 UTC, bqqbarbhg approved these changes
Good to go

2019-01-31 20:23 UTC, bqqbarbhg requested changes

2019-01-31 20:23 UTC, bqqbarbhg commented on server/src/setup.js
> +    config.databaseUrl = process.env.DATABASE_URL
Use the cached variable!

2019-01-31 23:44 UTC, quvide commented on server/src/setup.js
> +    config.databaseUrl = process.env.DATABASE_URL
good catch

2019-01-31 23:46 UTC, quvide commented on server/src/setup.js
> +    config.databaseUrl = process.env.DATABASE_URL
fixed it now

2019-02-06 12:25 UTC, HenrikHelenius commented
@bqqbarbhg check if ok now, re-approve

2019-02-06 12:27 UTC, bqqbarbhg approved these changes
YES

2019-02-06 12:56 UTC, tobbe-j commented
👍

2019-02-06 13:27 UTC, merged