Feature keybind
ktk-2005/Feedbacker-Forum pull request #43
Opened 2019-02-07 17:43 UTC by joonalillfors

2019-02-07 17:52 UTC, quvide requested changes

2019-02-07 17:52 UTC, quvide commented on client/src/components/comment-panel/comment-panel.js
> +          <form className={css('comment-form')} form="formie" onSubmit={this.handleSubmit}>
???

2019-02-07 17:52 UTC, quvide commented on client/src/globals.js
> +export function keyPressSubmit(e) {
Would it be better to give this event handler the submit button as an argument? It would be purer this way

2019-02-07 17:58 UTC, joonalillfors commented on client/src/components/comment-panel/comment-panel.js
> +          <form className={css('comment-form')} form="formie" onSubmit={this.handleSubmit}>
fixd

2019-02-07 18:00 UTC, joonalillfors commented on client/src/globals.js
> +export function keyPressSubmit(e) {
this way the place where this function is called needs less code and effort

2019-02-07 18:05 UTC, quvide commented on client/src/globals.js
> +export function keyPressSubmit(e) {
ok ok

2019-02-07 18:05 UTC, quvide approved these changes

2019-02-07 18:05 UTC, merged

2019-02-09 14:41 UTC, HenrikHelenius commented
![](https://github.trello.services/images/mini-trello-icon.png) [[task] [misc] Enter + ctrl submits form Joona](https://trello.com/c/bL5VzwTW/149-task-misc-enter-ctrl-submits-form-joona)