Changed timestamps and added ttimestamp tooltip
ktk-2005/Feedbacker-Forum pull request #60
Opened 2019-02-21 17:59 UTC by tobbe-j

Changed back timestamps to D-MM-YYYY HH:mm format.
Also added two hours to time to effset missing timezone data
in sqlite.
Added tooltip to timestamp with moment.fromNow formatting

2019-02-21 18:01 UTC, HenrikHelenius requested changes
todo

2019-02-21 18:01 UTC, HenrikHelenius commented on client/src/feedbacker-components/comment/comment.js
> +          add={{ hours: 2 }}
ADD TODO

2019-02-25 20:00 UTC, HenrikHelenius approved these changes

2019-02-25 21:20 UTC, kalomak approved these changes
🥴

2019-02-26 13:13 UTC, merged